version: '3.9'
services:
  db:
    image: postgres:16-alpine
    container_name: goldwallet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gold
      POSTGRES_PASSWORD: goldpass
      POSTGRES_DB: goldwallet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: goldwallet-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  pgdata:
